sudo: false
cache:
  bundler: true
  directories:
  - cache/
notifications:
  email: false
language: c
compiler: gcc
env:
- SDK_URL=https://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/generic/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
install:
- mkdir -p local
- cd local
- wget "http://us.archive.ubuntu.com/ubuntu/pool/main/c/ccache/ccache_3.1.6-1_amd64.deb"
- dpkg -x *.deb .
- cd ..
- mkdir -p cache
- cd cache
- wget -c $SDK_URL
- mkdir -p $TRAVIS_BUILD_DIR/sdk 
- cd $TRAVIS_BUILD_DIR/sdk
- tar xjf $TRAVIS_BUILD_DIR/cache/OpenWrt-SDK*.tar.bz2 -C .
- cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
- mkdir package/announce
- ln -s $TRAVIS_BUILD_DIR/Makefile package/announce/
- ln -s $TRAVIS_BUILD_DIR/src package/announce/
script:
- export PATH=$TRAVIS_BUILD_DIR/local/usr/bin:$PATH
- cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
- "./scripts/feeds update packages"
- "./scripts/feeds install libpthread"
- make V=s
- ls -la $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*/bin/ar71xx/packages/
deploy:
  provider: releases
  api_key:
    secure: secure: L5yTlbnfbQ1FWuvI/33nv2vSZNj3fAHPdQ2ORNB5lkrzrzdEDX66kLyygLVpIUm0ZeFhlKAujrXFh5w9Gu9v4E3fuhVBZZ13ZDuopyTWmJDTu/xGbb/10WlsixzXZqAgYwvv6XxPQ6CvEUV01lppS1+787bAbJhpJKUYebiD8H8=
  skip_cleanup: true
  file_glob: true
  file: "sdk/OpenWrt-SDK-*/bin/*"
  on:
    all_branches: true
