sudo: false
cache:
  bundler: true
  directories:
  - cache/
notifications:
  email: false
language: c
compiler: gcc
env:
- SDK_URL=https://downloads.openwrt.org/barrier_breaker/14.07-rc3/ar71xx/generic/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
install:
- apt-get install ccache
- mkdir -p cache
- cd cache
- wget -c $SDK_URL
- mkdir -p $TRAVIS_BUILD_DIR/sdk 
- cd $TRAVIS_BUILD_DIR/sdk
- tar xjvf $TRAVIS_BUILD_DIR/cache/OpenWrt-SDK*.tar.bz2 -C .
- cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
- mkdir package/announce
- ln -s $TRAVIS_BUILD_DIR/Makefile package/announce/
- ln -s $TRAVIS_BUILD_DIR/src package/announce/
script:
- cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
- "./scripts/feeds update packages"
- "./scripts/feeds install libpthread"
- make V=s
- ls -la $TRAVIS_BUILD_DIR/sdk/bin/ar71xx/packages/
deploy:
  provider: releases
  api_key:
    secure:
  skip_cleanup: true
  file_glob: true
  file: "sdk/bin/ar71xx/packages/announce*.ipk"
  on:
    tags: true
    all_branches: true
